source "https://rubygems.org"

gemspec

gem 'chef', "= 16.13.16"
gem 'chef-utils', "= 16.13.16" # mixlib-shellout currently floats on anything < 16.7.23
gem "chef_backup"
gem "omnibus-ctl"
gem "veil", git: "https://github.com/chef/chef_secrets.git"
gem "toml" # for habitat-land
